package Enums;

/**
 * Created by lap on 6/12/16.
 */
public enum HolderType {

    NOTE,ASSIGNMENT,POLL,EVENT,EMPTY,NEW_NOTE,GROUP_HEADER,GROUP_STICKY,COMMENT,

    PROGRESS_HEADER,PROGRESS_STICKY,PROGRESS,NOTIFICATION
}
